# Generated by Django 5.0.1 on 2024-01-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_alter_visit_place_pin_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit_place',
            options={'verbose_name': 'Visit Place'},
        ),
    ]
