# Generated by Django 5.0.1 on 2024-01-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
