# Generated by Django 4.2.6 on 2024-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='des_image',
            field=models.ImageField(default='', upload_to='package/image'),
        ),
    ]
