# Generated by Django 5.0.1 on 2024-01-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Citie'},
        ),
    ]
