# Generated by Django 5.0.1 on 2024-02-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Guide'), (3, 'Customer')], default=3),
        ),
    ]
